"""initial schema

Revision ID: ed987c277fa9
Revises: 
Create Date: 2026-05-24 15:55:00.123420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import crypto  # noqa: F401 — referenced by autogenerated EncryptedString/EncryptedNumeric/EncryptedJSON

# revision identifiers, used by Alembic.
revision: str = 'ed987c277fa9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('current_balance_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plaid_account_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('value_estimate_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('before_jsonb', crypto.EncryptedJSON(), nullable=True),
    sa.Column('after_jsonb', crypto.EncryptedJSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('monthly_revenue_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('monthly_expenses_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('net_margin_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('employer', sa.String(length=128), nullable=False),
    sa.Column('comp_total_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason_for_leaving', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_role', sa.String(length=128), nullable=False),
    sa.Column('current_employer', sa.String(length=128), nullable=False),
    sa.Column('current_comp_total_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('target_role', sa.String(length=128), nullable=True),
    sa.Column('target_comp_total_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('cert_or_milestone_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comp_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('metro', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('comp_p50_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('comp_p75_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('comp_p90_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary_encrypted', crypto.EncryptedString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('balance_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('apr_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('minimum_payment_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary_encrypted', crypto.EncryptedString(), nullable=False),
    sa.Column('principle', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target_amount_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('current_amount_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('cadence', sa.String(length=32), nullable=False),
    sa.Column('typical_gross_amount_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('tax_treatment_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rolling_4wk_avg_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiation_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('trigger_date', sa.Date(), nullable=False),
    sa.Column('related_role', sa.String(length=128), nullable=True),
    sa.Column('prep_notes_encrypted', crypto.EncryptedString(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assets_total_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('liabilities_total_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('net_worth_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('asset_breakdown_jsonb', crypto.EncryptedJSON(), nullable=True),
    sa.Column('liability_breakdown_jsonb', crypto.EncryptedJSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary_encrypted', crypto.EncryptedString(), nullable=False),
    sa.Column('vault_refs_jsonb', crypto.EncryptedJSON(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_estate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_encrypted', crypto.EncryptedString(), nullable=True),
    sa.Column('purchase_price_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('current_value_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('mortgage_balance_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('mortgage_apr_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('monthly_payment_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('property_type', sa.String(length=32), nullable=False),
    sa.Column('monthly_rent_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('equity_estimate_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retirement_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('ytd_contribution_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('balance_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('ytd_contribution_limit_remaining_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_deductions_1099',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('amount_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('evidence_note_encrypted', crypto.EncryptedString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(length=64), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('last4_encrypted', crypto.EncryptedString(), nullable=True),
    sa.Column('benefits_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credit_limit_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('autopay', sa.Boolean(), nullable=False),
    sa.Column('current_cycle_spend_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content_encrypted', crypto.EncryptedString(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cited_principle', sa.String(length=128), nullable=True),
    sa.Column('cited_vault_refs_jsonb', crypto.EncryptedJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('side_income_economics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_stream_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('hours_worked_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('expenses_jsonb', crypto.EncryptedJSON(), nullable=True),
    sa.Column('net_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('net_hourly_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['income_stream_id'], ['income_streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('cadence', sa.String(length=32), nullable=False),
    sa.Column('typical_amount_encrypted', crypto.EncryptedNumeric(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('side_income_economics')
    op.drop_table('messages')
    op.drop_table('cards')
    op.drop_table('tax_deductions_1099')
    op.drop_table('retirement_accounts')
    op.drop_table('real_estate')
    op.drop_table('patterns')
    op.drop_table('net_worth_snapshots')
    op.drop_table('negotiation_milestones')
    op.drop_table('income_streams')
    op.drop_table('goals')
    op.drop_table('decisions')
    op.drop_table('debts')
    op.drop_table('conversations')
    op.drop_table('comp_benchmarks')
    op.drop_table('career_position')
    op.drop_table('career_history')
    op.drop_table('business_income')
    op.drop_table('audit_log')
    op.drop_table('assets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
